version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: salad
      POSTGRES_PASSWORD: okok
      POSTGRES_DB: next-prisma-starter-new
    ports:
      - "5432:5432"
    
    restart: always