version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: salad
            POSTGRES_PASSWORD: okok
            POSTGRES_DB: devmize
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: